### ISSUE TITLE
Sending a message on Whatsapp Web logs you out

### ISSUE THREAD

**Issue by bigrand** [graysky2/profile-sync-daemon#349] opened 2023-01-13 21:49 UTC
You get this message when you send a message:

![image](https://user-images.githubusercontent.com/84900581/212425218-9b7a7f1a-8de6-497c-b1e4-834a3fb055dc.png)

 After stopping `psd.service` the problem disappears and you can now send messages without problem.

**Comment by bigrand** [comment] 2023-01-13 22:10
After reinstalling `profile-sync-daemon` package, the problem is fixed and I can no longer recreate the problem.

**Comment by bigrand** [comment] 2023-01-13 22:36
Seems I was mistaken. It's still a problem, a weird one.

After stopping and starting the service constantly and testing it more than a dozen times, it seems that the more you use Whatsapp Web the less likely you will get logged out. At first just sending messages logs you out, but after sending several files, spamming messages, etc. it seems it's "harder" to get logged out. 

I never managed to get logged out with the service inactive, every time I got logged out it was while `psd.service` was active.

**Comment by graysky2** [comment] 2023-01-14 11:05
How much RAM does your PC have?  See Q4 in the psd manpage.

**Comment by bigrand** [comment] 2023-01-14 20:41
My PC has 4 GBs. 

After changing `RuntimeDirectorySize` from 10% to 20%, it doesn't log me out anymore. Shouldn't 10% of 4 GBs be enough?

**Comment by graysky2** [comment] 2023-01-14 22:13
All depends on the size of your profile, look at the profile size from from `psd p` to see how large it is.

**Comment by bigrand** [comment] 2023-01-15 16:13
Even after uploading, downloading, spamming messages, and loading a dozen chats, it never exceeds 150 MBs, and 10% of 4 GBs should be around 400 MBs.

![2023-01-15T11:08:07,898587333-05:00](https://user-images.githubusercontent.com/84900581/212552350-e9013f21-1169-4663-aee9-2baf5fe95499.png)

**Comment by graysky2** [comment] 2023-01-15 17:43
I am just speculating ... I do not use WhatsApp.

**Comment by bigrand** [comment] 2023-01-15 17:47
When I opened `logind.conf`, `RuntimeDirectorySize` was commented. If it's commented, does it use 10% as default/fallback? I set it back to 10% and It works fine.

**Comment by graysky2** [comment] 2023-01-15 17:54
According the man page:
> Alternatively, a numerical percentage suffixed by "%" may be specified, which sets the size limit relative to the amount of physical RAM. Defaults to 10%

To me that means commented uses 10%

**Comment by ledufff** [comment] 2023-02-10 00:05
Yeah, I also have this issue,   apparently RuntimeDirectorySize=20% is a workaround.

**Comment by graysky2** [comment] 2023-03-17 07:52
I am tempted to close this as not a bug... memory requirements of plugins like whatsapp need to be considered when budgeting memory.  Feel free to re-open if you think this is not accurate or if there is something in my code causing the issue.

**Closed by graysky2** 2023-03-17 07:52 UTC
