### ISSUE TITLE
All browser profiles cannot be read

### ISSUE THREAD

**Issue by astatine** [graysky2/profile-sync-daemon#162] opened 2016-03-22 09:20 UTC
I am using the latest version of `psd` available from your PPA on my Ubuntu 15.10 x64 installation, with `overlayfs` enabled.

I recently updated to Linux kernel v4.5 and from around that time, something broke; `firefox-trunk` (Firefox Nightly) does not start at all, and `chromium-browser` complains that my preferences could not be read.

If I stop `psd.service`, Nightly works but as if with a completely fresh profile (with no addons, bookmarks, etc.). It is still using the same profile though.

I then started `psd.service` and created a completely fresh Nightly profile, but after a system reboot, Nightly refused to start once again.

**Comment by graysky2** [comment] 2016-03-22 18:43
What is the output of `psd p`?

**Comment by revealed** [comment] 2016-03-22 18:44
Hallo i just wanted to popp in here: Im using openSUSE. I built your version 6.21 here:
https://build.opensuse.org/package/show/home:revealed/profile-sync-daemon

It worked almost flawless for me with earlyer kernels now since my tumbleweed installation received kernel 4.5 also i can not enable overlayfs. It would kill all my browser profiles.

**Comment by graysky2** [comment] 2016-03-22 18:46
That is interesting.  I have not used 4.5.0 yet; perhaps they made changes to overlayfs?  I will build and test and report back in this task.

**Comment by revealed** [comment] 2016-03-22 18:46
Thank you so much. I enjoy the browsing expirience very much with your bash script ;)

**Comment by graysky2** [comment] 2016-03-22 18:50
Well, I am booted into 4.5.0 on Arch and am not experiencing anything unusual with psd and overlayfs.  Can you post the output of `psd p`?

**Comment by revealed** [comment] 2016-03-22 18:50
With enabled overlay or without?

**Comment by graysky2** [comment] 2016-03-22 18:50
With please.

**Comment by revealed** [comment] 2016-03-22 18:50
2 minutes please will edit in here

**Comment by graysky2** [comment] 2016-03-22 18:51
````
% psd p
Profile-sync-daemon v6.21 on Arch Linux

 Systemd service is currently active.
 Systemd resync-timer is currently active.
 Overlayfs v23 is currently active.

Psd will manage the following per /home/facade/.config/psd/.psd.conf:

 browser/psname:  chromium/chromium
 owner/group id:  facade/100
 sync target:     /home/facade/.config/chromium
 tmpfs dir:       /run/user/1000/facade-chromium
 profile size:    75M
 overlayfs size:  30M
 recovery dirs:   none
```

**Comment by revealed** [comment] 2016-03-22 18:54
oh what fail from me one moment ... any chance you are in an IRC somewhere?

**Comment by revealed** [comment] 2016-03-22 18:59
now finally managed to get what you asked for. Sorry for the inconvinience.

**Comment by graysky2** [comment] 2016-03-22 19:02
So it looks like your system crashed or was shutdown ungracefully.  You have the recovery directory for both of your browsers.  Stop psd.  Move the current profile one at a time to a new name and replace it with the recovery dir.  See the man page for details.

**Comment by revealed** [comment] 2016-03-22 19:06
I understand what you sugguest. But if i do that on every copy or restart of PSD e.g. chromium starts up with an empty like profile and an error dialogue box. In german: "Ihre Einstellungen können nicht gelesen werden. Einige Funktionen sind möglicherweise nicht verfügbar und Änderungen an Einstellungen werden nicht gespeichert."

In English this would mean (i can only translate):
Your settings can not be read. Some funcions are possibly not available und changes of settings will not be stored.

**Comment by revealed** [comment] 2016-03-22 19:14
Any chance you could tell me which last commit the overlayfs on your kernel got? Maybe i could find that for the openSUSE kernel?

**Comment by graysky2** [comment] 2016-03-22 20:13
Hmmm... so there is something jacked up in the kernel for both ubuntu and opensuse?  Arch doesn't modify the kernel as a rule (barring cirtical fixes/patches).

**Comment by revealed** [comment] 2016-03-22 20:20
i try asking for help on this on #suse i dont know how to approach this properly. I would appereciate every information from possible other distro which is affected in the same way. As told im just hobby linux user. Thx for you investigation on this.

**Comment by graysky2** [comment] 2016-03-22 20:25
So if you fix the profile manually and everything is good with overlayfs off... if you stop psd, enable overlayfs and start psd, you get an instant problem?  Post the output of `journalctl -b --user-unit=psd `

**Comment by revealed** [comment] 2016-03-22 20:28
Interesting:

-- Logs begin at So 2016-03-20 19:36:21 CET, end at Di 2016-03-22 21:27:13 CET. --                                                       
Mär 22 18:28:10 wild-thing systemd[2102]: Starting Profile-sync-daemon...
Mär 22 18:28:10 wild-thing systemd[2102]: Started Profile-sync-daemon.
Mär 22 19:51:29 wild-thing systemd[2102]: Stopping Profile-sync-daemon...
Mär 22 19:51:29 wild-thing profile-sync-daemon[8020]: firefox resync successful
Mär 22 19:51:30 wild-thing profile-sync-daemon[8020]: chromium resync successful
Mär 22 19:51:30 wild-thing profile-sync-daemon[8020]: chromium unsync successful
Mär 22 19:51:30 wild-thing profile-sync-daemon[8020]: firefox unsync successful
Mär 22 19:51:30 wild-thing systemd[2102]: Stopped Profile-sync-daemon.
Mär 22 19:51:32 wild-thing systemd[2102]: Starting Profile-sync-daemon...
Mär 22 19:51:32 wild-thing systemd[2102]: Started Profile-sync-daemon.
Mär 22 19:52:09 wild-thing systemd[2102]: Stopping Profile-sync-daemon...
Mär 22 19:52:09 wild-thing profile-sync-daemon[8562]: rsync: send_files failed to open "/home/disk/.mozilla/firefox/zge1lihb.default/.par
Mär 22 19:52:09 wild-thing profile-sync-daemon[8562]: rsync: send_files failed to open "/home/disk/.mozilla/firefox/zge1lihb.default/Site
Mär 22 19:52:09 wild-thing profile-sync-daemon[8562]: rsync: send_files failed to open "/home/disk/.mozilla/firefox/zge1lihb.default/addo
Mär 22 19:52:09 wild-thing profile-sync-daemon[8562]: rsync: send_files failed to open "/home/disk/.mozilla/firefox/zge1lihb.default/bloc
Mär 22 19:52:09 wild-thing profile-sync-daemon[8562]: rsync: send_files failed to open "/home/disk/.mozilla/firefox/zge1lihb.default/cert
Mär 22 19:52:09 wild-thing profile-sync-daemon[8562]: rsync: send_files failed to open "/home/disk/.mozilla/firefox/zge1lihb.default/comp
Mär 22 19:52:09 wild-thing profile-sync-daemon[8562]: rsync: send_files failed to open "/home/disk/.mozilla/firefox/zge1lihb.default/cont
Mär 22 19:52:09 wild-thing profile-sync-daemon[8562]: rsync: send_files failed to open "/home/disk/.mozilla/firefox/zge1lihb.default/cook
Mär 22 19:52:09 wild-thing profile-sync-daemon[8562]: rsync: send_files failed to open "/home/disk/.mozilla/firefox/zge1lihb.default/exte
Mär 22 19:52:09 wild-thing profile-sync-daemon[8562]: rsync: send_files failed to open "/home/disk/.mozilla/firefox/zge1lihb.default/exte
Mär 22 19:52:09 wild-thing profile-sync-daemon[8562]: rsync: send_files failed to open "/home/disk/.mozilla/firefox/zge1lihb.default/heal
Mär 22 19:52:09 wild-thing profile-sync-daemon[8562]: rsync: send_files failed to open "/home/disk/.mozilla/firefox/zge1lihb.default/key3
Mär 22 19:52:09 wild-thing profile-sync-daemon[8562]: rsync: send_files failed to open "/home/disk/.mozilla/firefox/zge1lihb.default/mime
Mär 22 19:52:09 wild-thing profile-sync-daemon[8562]: rsync: send_files failed to open "/home/disk/.mozilla/firefox/zge1lihb.default/perm
Mär 22 19:52:09 wild-thing profile-sync-daemon[8562]: rsync: send_files failed to open "/home/disk/.mozilla/firefox/zge1lihb.default/plac
Mär 22 19:52:09 wild-thing profile-sync-daemon[8562]: rsync: send_files failed to open "/home/disk/.mozilla/firefox/zge1lihb.default/plug
Mär 22 19:52:09 wild-thing profile-sync-daemon[8562]: rsync: send_files failed to open "/home/disk/.mozilla/firefox/zge1lihb.default/pref
Mär 22 19:52:09 wild-thing profile-sync-daemon[8562]: rsync: send_files failed to open "/home/disk/.mozilla/firefox/zge1lihb.default/revo
Mär 22 19:52:09 wild-thing profile-sync-daemon[8562]: rsync: send_files failed to open "/home/disk/.mozilla/firefox/zge1lihb.default/sear
Mär 22 19:52:09 wild-thing profile-sync-daemon[8562]: rsync: send_files failed to open "/home/disk/.mozilla/firefox/zge1lihb.default/secm
Mär 22 19:52:09 wild-thing profile-sync-daemon[8562]: rsync: send_files failed to open "/home/disk/.mozilla/firefox/zge1l

**Comment by revealed** [comment] 2016-03-22 20:38
graysky2 please do not kick my rear part. But magically on the felt 20 th restart for this session with enabled overlay module it works now suddenly.

**Comment by graysky2** [comment] 2016-03-22 20:47
So everything is working?

**Comment by revealed** [comment] 2016-03-22 20:52
Im still trying. On my "host" its working. I have a VM setup with the same error. I tryed a newer vanilla kernel on it with the same error. I m like rebooting now to test fresh. (weird) Maybe i installed any update im not aware of. I will see if that same is the case in the VM. Then it would be solved for me. I let you know.

**Comment by revealed** [comment] 2016-03-22 21:00
Ok - VM now suddenly alsow working after updates. Theres just the big problem that i can not track down which simple fix held what could fix it for others. Thats the bad now.

**Comment by astatine** [comment] 2016-03-23 10:19
@revealed: :+1: _Ich habe kein Problem_ with your input in this thread.

@graysky2: I can confirm that my problems have disappeared with `overlayfs` disabled. I needed a Nightly profile refresh anyway. Is there anything else I can do to help you debug this issue?

**Comment by revealed** [comment] 2016-03-23 15:48
Thank you for the understanding. I sadly have to say the issue is back. Yesterday until now it seemed to work fine. And now, like one of those sporadic errors (which i can not see in the logs) it started to happen again. I get that error dialogue mentioned above and the profiles get destroyed. As workaround i will continue to use it with disabled overlayfs.

**Comment by graysky2** [comment] 2016-03-23 18:51
I cannot reproduce this on my system running 4.5.0 albeit a different distro.  First thing I want to verify is that you are able to run it stably under a different kernel to rule out something else.  Can you downgrade your kernel to the 4.4 series or to the 4.1 lts series and run the system normally to see if it comes back?

**Comment by revealed** [comment] 2016-03-23 19:14
i have 4.4.3.1 in multiversion left in the VM from last snapshot. Indeed i booted it and it works with enabled overlayfs. A direct testing from this point booting the 4.5.0.4 again: Firefox says Secure Connection Failed. (Whatever this means) -- something with the profile is messed. So i think you are very right expecting theres something wrong with the overlayfs module.

**Comment by revealed** [comment] 2016-03-23 19:34
I see no further thing currently than trying it this way: https://bugzilla.opensuse.org/show_bug.cgi?id=972394

If you have further ideas i would much appericiate. I dont know if they can help me. Thank you.

**Comment by Schattenjager-RC** [comment] 2016-04-20 12:40
I had the same problem on Ubuntu after upgrading the kernel to version 4.5.0 and up.
But the kernel was updated today to version 4.5.2 and the problem disappeared.
I found the following line in the changelog, not sure if it is related:
`btrfs: fix crash/invalid memory access on fsync when using overlayfs`
Now everything works fine)

**Comment by revealed** [comment] 2016-04-21 08:15
Hallo. I have even tested a future kernel for openSUSE. It seems to contain this fix also. I just can not find the exact description in the RPM's changelog. But it is seemingly: commit de17e793b104d690e1d007dfc5cb6b4f649598ca upstream. I will submit this info in my bugreport in openSUSE bugzilla.

**Comment by graysky2** [comment] 2016-04-22 21:06
Is it a fair assessment that this issue is not related to psd?

**Comment by Schattenjager-RC** [comment] 2016-04-23 05:23
Yes, I agree entirely.

**Comment by revealed** [comment] 2016-04-23 11:45
Graysky2. I just want to thank you again for this nice Tool. It improves my webbrowser performance very much. Unbound from the bottleneck of an old HDD. E.g. my old 2008 Notebook performs like a quite recent One. Btw. It could also have been the case i had failed packaging.

**Comment by graysky2** [comment] 2016-04-23 16:41
You're welcome.  Enjoy.  Closing.

**Closed by graysky2** 2016-04-23 16:41 UTC
Labels: General support
