### ISSUE TITLE
Firefox extensions don't work if overlayfs is in use on top of btrfs

### ISSUE THREAD

**Issue by jaro3** [graysky2/profile-sync-daemon#249] opened 2019-09-25 15:08 UTC
both floccus and passman get resets and/or locked by passwords and their de novo setting gets lost on browser exit :-(   same with adblock and perhaps more  WTF?

**Comment by graysky2** [comment] 2020-04-12 17:12
Is it a permissions issue with the overlayfs?

**Comment by graysky2** [comment] 2020-04-21 21:27
@jaro3 - Can you confirm this is still an issue?

**Comment by jaro3** [comment] 2020-04-23 12:21
It's an issue with btrfs specifically, overlayfs is not compatible with btrfs.....

**Comment by graysky2** [comment] 2020-04-23 19:31
Can you edit the title to include the btrfs observation?  I may add a check for it and refuse to start if btrfs is present.

**Comment by graysky2** [comment] 2020-05-05 20:44
@jaro3 - Ping

**Comment by jaro3** [comment] 2020-05-07 02:34
I have moved to new kernel meanwhile, will check again when time available, I am using it without the overlayfs since the trouble....

**Comment by graysky2** [comment] 2020-05-08 17:17
Please try it so we can close this or verify that it is in fact a bug.

**Comment by jaro3** [comment] 2020-05-10 03:08
It's still there.  I turn on overlayfs and all is gone, bookmarks, extensions etc....  turn it off and it works.
nextcloud-app-mozilla_sync 1.4-1
kernel 5.6.1
![Screenshot from 2020-05-10 12-00-54](https://user-images.githubusercontent.com/12386887/81489971-85131e00-926b-11ea-9ea9-d15b6dbd8fad.png)

**Comment by graysky2** [comment] 2020-05-10 11:55
Which kernel? `uname -a`

**Comment by graysky2** [comment] 2020-05-10 12:25
To test, I created a btrfs partition on a USB stick, mounted it to `~/.mozilla/` and setup firefox with an extension (some adblocker), made some bookmarks, and customized the theme.  Then I set psd to manage the browser with overlayfs and started psd.  I saw no differences, adblock was there, theme was there, bookmarks and history were all there.

```
% mount | grep btrf
/dev/sdc1 on /home/facade/.mozilla type btrfs (rw,relatime,space_cache,subvolid=5,subvol=/)
```

```
% ustatus psd ; ustatus psd-resync ; systemctl --user list-timers
● psd.service - Profile-sync-daemon
     Loaded: loaded (/usr/lib/systemd/user/psd.service; enabled; vendor preset: enabled)
     Active: active (exited) since Sun 2020-05-10 08:24:08 EDT; 1s ago
       Docs: man:psd(1)
             man:profile-sync-daemon(1)
             https://wiki.archlinux.org/index.php/Profile-sync-daemon
    Process: 13114 ExecStart=/usr/bin/profile-sync-daemon startup (code=exited, status=0/SUCCESS)
   Main PID: 13114 (code=exited, status=0/SUCCESS)

May 10 08:24:08 ease systemd[940]: Starting Profile-sync-daemon...
May 10 08:24:08 ease profile-sync-daemon[13114]: psd startup check successful
May 10 08:24:08 ease systemd[940]: Finished Profile-sync-daemon.
● psd-resync.service - Timed resync
     Loaded: loaded (/usr/lib/systemd/user/psd-resync.service; disabled; vendor preset: enabled)
     Active: inactive (dead) since Sun 2020-05-10 08:24:08 EDT; 1s ago
TriggeredBy: ● psd-resync.timer
    Process: 13177 ExecStart=/usr/bin/profile-sync-daemon resync (code=exited, status=0/SUCCESS)
   Main PID: 13177 (code=exited, status=0/SUCCESS)

May 10 08:24:08 ease systemd[940]: Starting Timed resync...
May 10 08:24:08 ease profile-sync-daemon[13177]: firefox sync successful
May 10 08:24:08 ease profile-sync-daemon[13177]: firefox sync successful
May 10 08:24:08 ease systemd[940]: psd-resync.service: Succeeded.
May 10 08:24:08 ease systemd[940]: Finished Timed resync.
NEXT                        LEFT       LAST PASSED UNIT             ACTIVATES         
Sun 2020-05-10 09:24:08 EDT 59min left n/a  n/a    psd-resync.timer psd-resync.service

1 timers listed.
Pass --all to see loaded but inactive timers, too.
```

**Comment by jaro3** [comment] 2020-05-10 13:13
uname -a
Linux SERVER 5.6.1-pf #1 SMP PREEMPT Thu Apr 9 10:53:37 JST 2020 x86_64 GNU/Linux

can re-test with the stock but I don't see any difference in the btrfs and overlayfs modules
I also use the floccus extension with nextcloud bookmarks on the same machine which doesn't work properly even if overlayfs is disabled but that may not be related to psd

**Comment by graysky2** [comment] 2020-05-10 15:02
> I also use the floccus extension with nextcloud bookmarks on the same machine which doesn't work properly even if overlayfs is disabled but that may not be related to psd

If it's not working without psd running I would agree.

**Comment by jaro3** [comment] 2020-05-18 08:04
fixed the bookmarks issue, it was mbstring configuration and using multiple browsers with same bookmarks making duplicates....

BUT the overlayfs doesn't still work, everything fine and I turn it on and loose bookmarks and other settings, passman get locked etc....  firefox reporting this:

![Screenshot from 2020-05-18 16-53-11](https://user-images.githubusercontent.com/12386887/82188824-fc852500-98dd-11ea-8717-f9b792e67b2f.png)

kernel 5.6.1-pf
firefox 76.0-2
icecat 68.8.0-1

**Comment by jaro3** [comment] 2020-05-18 08:13
fixed the bookmarks issue, it was mbstring configuration and using multiple browsers with same bookmarks making duplicates....

BUT the overlayfs doesn't still work, everything fine and I turn it on and loose bookmarks and other settings, passman get locked etc....  firefox reporting this:

![Screenshot from 2020-05-18 16-53-11](https://user-images.githubusercontent.com/12386887/82188824-fc852500-98dd-11ea-8717-f9b792e67b2f.png)

kernel 5.6.1-pf
firefox 76.0-2
icecat 68.8.0-1

double confirmed with:

very stock kernel 5.6.10-arch1-1 and firefox 76.0-2

exactly same message

**Comment by graysky2** [comment] 2020-05-18 10:07
I cannot reproduce.  Tried again.  See above.

**Comment by jaro3** [comment] 2020-05-18 10:14
my btrfs is on top of dmcrypt if this could make a difference

**Comment by jaro3** [comment] 2020-05-18 10:16
well and compression + COW is on in btrfs

**Comment by graysky2** [comment] 2020-05-18 10:24
Can you simplify and verify that the condition I reported above works for you?
> To test, I created a btrfs partition on a USB stick, mounted it to ~/.mozilla/ and setup firefox with an extension (some adblocker), made some bookmarks, and customized the theme. Then I set psd to manage the browser with overlayfs and started psd. I saw no differences, adblock was there, theme was there, bookmarks and history were all there.

**Comment by b0o** [comment] 2020-05-28 01:08
Chiming in: I don't have any of these issues with psd w/ overlayfs on top of btrfs (on top of dm-crypt).

**Comment by jaro3** [comment] 2020-05-28 02:41
what are your btrfs mount options cat /etc/mtab?

**Comment by graysky2** [comment] 2020-05-28 09:37
@jaro3 - Based on my testing on btrfs and based on @b0o 's experience, I am wondering the issue is with something on your system not with the code here.  Please try my [USB stick suggestion](https://github.com/graysky2/profile-sync-daemon/issues/249#issuecomment-630091431) and report back.

**Comment by jaro3** [comment] 2020-05-28 17:13
when I have time to play with it, I need a usable production system now and there were too many failures of the overlayfs for me.. isn't there any detailed debug log somewhere when it spewing those errors?

**Comment by graysky2** [comment] 2020-05-29 08:56
@jaro3 - Based on my test above, and based on @b0o's results, I am concluding that psd isn't to blame for the issues you are experiencing.  The USB stick experiment I proposed is easy (you're just temporarily renaming your `~/.mozilla/` and replacing it simplified btrfs option) to do and shouldn't affect your system stability.  It should help us directly test psd + btrfs + overlayfs on your system, but since you are unwilling to test it, I am going to close this ticket.  Feel free to request a reopen if you do the work and find that it is still an issue.

**Closed by graysky2** 2020-05-29 08:56 UTC
Labels: Awaiting feedback
