### ISSUE TITLE
electron / embedded chrome applications

### ISSUE THREAD

**Issue by elebertus** [graysky2/profile-sync-daemon#358] opened 2023-05-22 18:28 UTC
For example slack for linux, runs chrome and such.

It looks easy enough to fork and implement, but what are the thoughts on this in general? Would this be something desirable?

**Comment by graysky2** [comment] 2023-05-23 06:14
I am unfamiliar with electron and embedded chrome apps

**Comment by Freso** [comment] 2023-05-31 22:38
Possibly duplicate of https://github.com/graysky2/profile-sync-daemon/issues/309 ?

**Comment by graysky2** [comment] 2023-06-03 12:13
It is a dup

**Closed by graysky2** 2023-06-03 12:13 UTC
