### ISSUE TITLE
Recursive symlink in sync target

### ISSUE THREAD

**Issue by telephone** [graysky2/profile-sync-daemon#138] opened 2015-09-17 09:39 UTC
I've noticed that in the synced profile there's a repetitive/recursive symlink. I haven't tested whether this is exclusive to Opera, or is global.

```
sync target:     /home/<user>/.config/opera-developer
tmpfs dir:       /run/user/1000/<user>-opera-developer
```

Within the sync target exists a symlink `<user>-opera-developer` (full path `/home/<user>/.config/opera-developer/<user>-opera-developer`). This symlink points to the tmpfs directory, but the symlink itself is recursive.

For example, the following is a valid:

```
/home/<user>/.config/opera-developer/<user>-opera-developer/<user>-opera-developer/<user>-opera-developer/<user>-opera-developer/<user>-opera-developer/<user>-opera-developer
```

Now I'm unsure why another symlink is created within the sync target, when the sync target itself is already a symlink to the tmpfs dir.

**Comment by graysky2** [comment] 2015-09-17 09:44
Thanks for pointing it out.  The reporter of #137 has seen it too ... trying to replicate on my system.

**Comment by graysky2** [comment] 2015-09-17 09:49
@Nefelim4ag 
Any thoughts?  Seeing this on your system?

**Comment by graysky2** [comment] 2015-10-26 19:59
@telephone - I think I found the cause of this pesky bug: it happens when the VOLATILE variable was unset when trying to safe guard against a user modifying the config file.  Are you able to try my unstable branch?  If running Arch, here is a PKGBUILD for it: https://aur.archlinux.org/packages/profile-sync-daemon-git/

**Comment by graysky2** [comment] 2015-10-27 05:41
Fixed in https://github.com/graysky2/profile-sync-daemon/commit/d103bafe5e120dd46e0b371b06037a6e01d7ee4e

**Closed by graysky2** 2015-10-27 05:41 UTC
Labels: Bug
