### ISSUE TITLE
psd fails if /sbin or /usr/sbin is not in PATH

### ISSUE THREAD

**Issue by JanLuca** [graysky2/profile-sync-daemon#217] opened 2018-02-03 13:10 UTC
In profile-sync-daemon there are multiple calls to modinfo. This calls fails if /sbin or /usr/sbin is not in PATH. Could you use the absolute path to the tools used so they do not depend on the environment?

Thank you in advance,
Jan

**Comment by graysky2** [comment] 2018-02-03 13:26
The script depends on many dependencies being in the path, for example, rsync, awk, modinfo, etc.  I am trying to imagine a setup in which one would not was those paths in the global $PATH...

**Comment by behrmann** [comment] 2018-02-03 13:32
The issue is rather, that the calls to modinfo fail if /usr is not merged. On arch modinfo is situated in `/usr/bin` and not in `/usr/sbin`, where it is in Debian and `/usr/sbin` is not necessarily in the `$PATH` for historical reasons.

**Comment by behrmann** [comment] 2018-02-03 14:00
Having debuged the problem a bit further the problem is a bit less clear. We will report back with more info.

**Comment by graysky2** [comment] 2018-02-03 14:19
> The issue is rather, that the calls to modinfo fail if /usr is not merged. On arch modinfo is situated in /usr/bin and not in /usr/sbin, where it is in Debian, and /usr/sbin is not necessarily in the $PATH for historical reasons.

I don't understand that.... if you put modinfo in /foo/bar and if /foo/bar is in your path, it works.  If not, it doesn't work.  Your global vars don't seem to be right for whatever reason.

**Closed by graysky2** 2018-02-03 14:19 UTC

**Comment by eMPee584** [comment] 2020-01-18 16:29
On debian `modinfo` is in `/sbin`, which is not in a normal user's path.
