### ISSUE TITLE
Losing both firefox and chromium profiles - multiple users

### ISSUE THREAD

**Issue by RobDean69** [graysky2/profile-sync-daemon#119] opened 2015-05-31 10:23 UTC
Same issue as with case number #118. Two user Kubuntu system, one user has chromium profile synced with profile-sync-daemon the second user doesn't. First user logs in, profile is all ok. Logs out and second user logs in, still all ok. Second user logs out, first user logs back in again and when chromium is launched it starts with a new profile. The workaround is - first user logs in, all ok. Second user logs in, all ok. Re-boot machine and first user logs in, all ok. Profile-sync-daemon has been installed from source with the "make install-systemd-all" command.

**Comment by graysky2** [comment] 2015-05-31 11:18
Is it 15.04?  If so, did you build psd with the `make-systemd-all` so you're using the native systemd service?

**Comment by RobDean69** [comment] 2015-05-31 12:06
It is 15.04. I used the command [code]make install-systemd-all[/code]. [code]make-systemd-all[/code] gives me "command not found". What is the correct way to build and install? I'm guessing it's not installed correctly as when I reboot the machine PSD doesn't start by itself, I have to run it manually from a command line.

**Comment by RobDean69** [comment] 2015-05-31 12:14
Could you possibly give instructions on how to completely remove PSD from my system then reinstall it from source? I'm wondering if maybe something was left behind from when I installed from the PPA and that is causing an issue?

**Comment by graysky2** [comment] 2015-05-31 15:11
For ubuntu, uninstall by stopping psd.  Then `apt-get remove profile-sync-daemon`.  Now to install, download the source tarball (https://github.com/graysky2/profile-sync-daemon/archive/v5.73.tar.gz) and extract it.  Now run `make` then `sudo make install-systemd-all` from the dir you extracted it.

Verify that `/etc/psd.conf` is setup to you liking then start the systemd service `sudo systemctl start psd`.  You can enable the service by running `sudo systemctl enable psd`.

**Comment by RobDean69** [comment] 2015-06-01 05:16
Followed these instructions (thanks graysky2 for the simple to follow steps)  but problem is still occurring.

**Comment by graysky2** [comment] 2015-06-01 23:54
Well, we need to figure out what is different on your system. Do you have an encrypted /home partition?

BTW, I readded packages for Ubuntu 15.04+ in my PPA.  Please try it on your 15.04 box.  It worked on my 15.04 VM.

**Comment by RobDean69** [comment] 2015-06-02 10:09
I installed the packages from the PPA and initial testing shows the problem is gone. Not sure why the packages from the PPA would be different, or install differently from building from source?

**Comment by graysky2** [comment] 2015-06-02 19:02
I don't know what the cause of your issues might be; I have tried to reproduce on my Arch system but cannot.  Glad the PPA package works for you.  I will close this now. Request to reopen if needed.

**Closed by graysky2** 2015-06-02 19:02 UTC
