### ISSUE TITLE
6.28 gives me an wrong variable?:

### ISSUE THREAD

**Issue by revealed** [graysky2/profile-sync-daemon#188] opened 2016-11-22 18:41 UTC
$ psd preview
resulting in:
/usr/bin/psd: Zeile 359: ${#DIRArr[@]##*/}: Falsche Variablenersetzung.

Translates ~ like Line 359 wrong Variable set?

I think i will skip back to 6.25 in the meantime. Thank you very much for this great tool.

**Comment by revealed** [comment] 2016-11-22 18:50
Uhm i fear this could be a issue in my distro. I have to review this once more. Maybe a glitch in Tumbleweed.

**Comment by revealed** [comment] 2016-11-22 19:26
Ah i found this:
https://github.com/graysky2/profile-sync-daemon/pull/185
Think im having the same issue.

But i run into another problem, assuming another line needs the change also :
 https://github.com/graysky2/profile-sync-daemon/commit/768c1552f7bf39b43aab9178cffa4f2af9467337

**Comment by graysky2** [comment] 2016-11-22 20:23
Which browsers are you trying to manage?  What version of bash does your distro that gives the error above ship with? `bash --version`

**Comment by revealed** [comment] 2016-11-22 20:54
bash --version
GNU bash, Version 4.4.0(1)-release (x86_64-suse-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.

Chromium and Firefox.

**Comment by graysky2** [comment] 2016-11-22 20:57
I am on bash 4.4.5 and either gives the desired effect:
```
$ DIRArr=('/foo/bar' '/foo/tit')
$ echo "${DIRArr[@]##*/}" | sed 's/ /\n/g' | sort -u | wc -l
2

$ echo "${DIRArr[@]}" | sed 's/ /\n/g' | sort -u | wc -l
2
```

What is the bash version your distro runs?  Can you try the above code and post the results as I have please?

**Comment by revealed** [comment] 2016-11-22 21:12
[General]
StartWithLastProfile=1

[Profile0]
Name=default
IsRelative=1
Path=crazynumber.default
Default=1

**Comment by graysky2** [comment] 2016-11-23 14:53
Would be good to merge the discussion but I have no idea how to do it :simple_smile:

**Comment by graysky2** [comment] 2016-11-23 14:59
I am also not able to reproduce the issue you're describing.  Can you simplify the config defining BROWSERS="firefox" and post the output of `psd p` on the machine that gives this error?  Still present?

**Comment by revealed** [comment] 2016-11-23 19:46
I decided to begin from 0. I created a testing playground, and redownloaded the source. Im currently building a rpm. When done i will install it manually. (Not public available). Then i will try. Just because i was playing around with the /usr/bin/psd after i faced the issue.

https://build.opensuse.org/package/show/home:revealed:testing/profile-sync-daemon

Will report back from scratch with output of '$ psd p', as soon as im done.

**Comment by revealed** [comment] 2016-11-23 19:57
I hope you do not hate me for this now. I can not reproduce the issue since i replaced the source file with a fresh downloaded. Also there where some updates to the Tumbleweed snapshot. So i can not tell what all got changed. But all is working fine again. And i will push this change to my normal home playground (repo) available public. Look:

![nomoreerror](https://cloud.githubusercontent.com/assets/3414736/20576673/24a7189a-b1bf-11e6-97c2-ee31383d01a5.png)

So i think the issue is really closed. Sorry i stole your time. And thank you very much for your help.

**Comment by graysky2** [comment] 2016-11-23 20:10
It's fine; glad you're functional again.  Please close the issue when you verified it isn't my stuff.

**Comment by revealed** [comment] 2016-11-23 20:31
Absolutely not your Stuff 👍

**Closed** 2016-11-23 20:33 UTC
Labels: General support
