### ISSUE TITLE
Chromium writing data to disk

### ISSUE THREAD

**Issue by andresmrm** [graysky2/profile-sync-daemon#172] opened 2016-06-03 19:00 UTC
It seems Chromium 51.0.2704.63 (64-bit) is leaking data to disk...
Profile-sync-daemon v6.22
Using Arch Linux.
BROWSERS="firefox chromium"
Both browsers seem to mount right when checking with "psd p".

Firefox seem so work ok. I can navigate and nothing seems to be written to disk.
But when I navigate with Chromium, it seems to keep writing to disk.

**Comment by graysky2** [comment] 2016-06-03 19:19
How are you assessing that data are leaking out to the disk?  Post the output of `psd p`

**Comment by andresmrm** [comment] 2016-06-03 22:00
With: `cat /sys/fs/.../lifetime_write_kbytes`

```
$ psd p

Profile-sync-daemon v6.22 on Arch Linux

 Systemd service is currently active.
 Systemd resync-timer is currently active.
 Overlayfs v23 is currently active.

Psd will manage the following per /home/user/.config/psd/.psd.conf:

 browser/psname:  firefox/firefox
 owner/group id:  user/1000
 sync target:     /home/user/.mozilla/firefox/d385c294.default
 tmpfs dir:       /run/user/1000/user-firefox-d385c294.default
 profile size:    177M
 overlayfs size:  21M
 recovery dirs:   none

 browser/psname:  chromium/chromium
 owner/group id:  user/1000
 sync target:     /home/user/.config/chromium
 tmpfs dir:       /run/user/1000/user-chromium
 profile size:    113M
 overlayfs size:  62M
 recovery dirs:   none
```

**Comment by graysky2** [comment] 2016-06-04 00:36
Do we know that catting that file is aware of the overlayfs mount?

**Comment by andresmrm** [comment] 2016-06-04 01:10
I would say that yes, because the "catted" number doesn't change when using Firefox or modifing other mounted files (except when auto backup is done or unmounting happens).
Just checked the `Total_LBAs_Written` using `smartctl` and it's also changing when using Chromiun...
What method do you use to check if anything was written to a disk?

Also, do you know a got method to detect which process wrote to which disk? I'm using iotop, but there are many writes that it doesn't capture, and it has no info about to which disk the writes were.

**Comment by graysky2** [comment] 2016-06-04 12:19
Again, I do not know if the method you're using is aware of overlayfs mounts.  They are special.

**Comment by ActualizeInMaterial** [comment] 2016-06-20 02:49
You could try:

```bash
# echo 1 > /proc/sys/vm/block_dump
# dmesg -w
```

And you see things like this:

```
[ 9910.807103] Compositor(22003): dirtied inode 1206255 (?) on tmpfs
[ 9910.808112] Compositor(22003): dirtied inode 1206257 (?) on tmpfs
[ 9910.808550] CompositorTileW(22007): dirtied inode 1206252 (?) on tmpfs
[ 9910.809319] CompositorTileW(22006): dirtied inode 1206253 (?) on tmpfs
[ 9910.809459] CompositorTileW(22004): dirtied inode 1206254 (?) on tmpfs
[ 9929.002126] BrowserBlocking(21853): dirtied inode 1203853 (?) on tmpfs

```

**Comment by andresmrm** [comment] 2016-06-20 23:23
Thanks, @ActualizeInMaterial.

I got messages like this:

	[ 3155.133732] chromium(31986): dirtied inode 206515 (?) on tmpfs
	[ 3155.134207] chromium(31986): dirtied inode 206516 (?) on tmpfs
	[ 3155.134809] chromium(31986): dirtied inode 204740 (?) on tmpfs
	[ 3155.180558] BrowserBlocking(31897): dirtied inode 208478 (https_www.google.com.br_0.localstorage-journal) on tmpfs
	[ 3155.180687] BrowserBlocking(31897): dirtied inode 62995 (https_www.google.com.br_0.localstorage) on tmpfs
	[ 3155.206577] chromium(31986): dirtied inode 202597 (?) on tmpfs
	[ 3155.206623] chromium(31986): dirtied inode 204750 (?) on tmpfs
	[ 3155.206671] chromium(31986): dirtied inode 202599 (?) on tmpfs
	[ 3155.206914] chromium(31986): dirtied inode 200361 (?) on tmpfs
	[ 3155.206991] chromium(31986): dirtied inode 206521 (?) on tmpfs
	[ 3155.266850] chromium(31986): dirtied inode 208483 (?) on tmpfs
	[ 3155.267444] chromium(31986): dirtied inode 208486 (?) on tmpfs
	[ 3155.267788] chromium(31986): dirtied inode 208485 (?) on tmpfs
	[ 3155.268116] chromium(31986): dirtied inode 208484 (?) on tmpfs
	[ 3155.319913] SimpleCacheWork(32104): dirtied inode 206524 (?) on tmpfs
	[ 3155.330756] Chrome_IOThread(31903): dirtied inode 202618 (?) on tmpfs
	[ 3155.357177] chromium(31986): dirtied inode 204741 (?) on tmpfs
	[ 3155.367536] chromium(32222): dirtied inode 200475 (?) on tmpfs
	[ 3155.367701] chromium(32222): dirtied inode 200476 (?) on tmpfs
	[ 3155.402044] chromium(31998): dirtied inode 200477 (?) on tmpfs
	[ 3155.403655] chromium(31998): dirtied inode 204770 (?) on tmpfs
	[ 3155.409722] chromium(32222): dirtied inode 202620 (?) on tmpfs
	[ 3155.413069] chromium(31998): dirtied inode 202619 (?) on tmpfs
	[ 3155.413435] chromium(31998): dirtied inode 202621 (?) on tmpfs
	[ 3155.469895] chromium(31986): dirtied inode 204742 (?) on tmpfs
	[ 3155.561847] chromium(31986): dirtied inode 204739 (?) on tmpfs
	[ 3155.699850] chromium(31998): dirtied inode 206526 (?) on tmpfs
	[ 3156.023078] Chrome_IOThread(31903): dirtied inode 206527 (?) on tmpfs
	[ 3156.062869] chromium(31986): dirtied inode 206529 (?) on tmpfs
	[ 3156.137780] chromium(32222): dirtied inode 207402 (?) on tmpfs
	[ 3156.138629] chromium(32222): dirtied inode 202622 (?) on tmpfs
	[ 3156.233873] Chrome_DBThread(31898): dirtied inode 11665664 (?) on dm-0
	[ 3156.233879] Chrome_DBThread(31898): dirtied inode 11665664 (?) on dm-0
	[ 3156.267937] Chrome_IOThread(31903): dirtied inode 202636 (?) on tmpfs
	[ 3156.276429] Chrome_IOThread(31903): dirtied inode 206542 (?) on tmpfs
	[ 3156.278489] chromium(32184): dirtied inode 206541 (?) on tmpfs
	[ 3156.295915] chromium(32222): dirtied inode 202634 (?) on tmpfs
	[ 3156.296189] chromium(32222): dirtied inode 202635 (?) on tmpfs
	[ 3156.296627] chromium(32222): dirtied inode 206543 (?) on tmpfs
	[ 3156.296964] chromium(32222): dirtied inode 206544 (?) on tmpfs
	[ 3156.297332] chromium(32222): dirtied inode 206545 (?) on tmpfs
	[ 3156.297470] chromium(32184): dirtied inode 206546 (?) on tmpfs
	[ 3156.306550] chromium(31986): dirtied inode 201365 (?) on tmpfs
	[ 3156.306813] chromium(31986): dirtied inode 201366 (?) on tmpfs
	[ 3156.307089] chromium(31986): dirtied inode 201367 (?) on tmpfs
	[ 3156.307337] chromium(31986): dirtied inode 201368 (?) on tmpfs
	[ 3156.326577] termite(1351): dirtied inode 207403 (?) on tmpfs
	[ 3156.379686] CompositorTileW(32229): dirtied inode 206550 (?) on tmpfs
	[ 3156.379693] CompositorTileW(32230): dirtied inode 206549 (?) on tmpfs
	[ 3156.379964] chromium(31986): dirtied inode 201370 (?) on tmpfs
	[ 3156.380415] CompositorTileW(32230): dirtied inode 203553 (?) on tmpfs
	[ 3156.429812] chromium(31986): dirtied inode 201374 (?) on tmpfs
	[ 3156.430133] chromium(31986): dirtied inode 201373 (?) on tmpfs
	[ 3156.449232] CompositorTileW(32227): dirtied inode 201371 (?) on tmpfs
	[ 3156.449286] CompositorTileW(32230): dirtied inode 201372 (?) on tmpfs
	[ 3156.449682] CompositorTileW(32229): dirtied inode 204784 (?) on tmpfs
	[ 3156.451696] chromium(31986): dirtied inode 208492 (?) on tmpfs
	[ 3156.451971] chromium(31986): dirtied inode 208493 (?) on tmpfs
	[ 3156.452236] chromium(31986): dirtied inode 208494 (?) on tmpfs
	[ 3156.452501] chromium(31986): dirtied inode 208495 (?) on tmpfs
	[ 3156.452766] chromium(31986): dirtied inode 208496 (?) on tmpfs
	[ 3156.453042] chromium(31986): dirtied inode 200497 (?) on tmpfs
	[ 3156.453060] chromium(31986): dirtied inode 208497 (?) on tmpfs
	[ 3156.521266] Chrome_IOThread(31903): dirtied inode 200498 (?) on tmpfs
	[ 3156.629315] chromium(32222): dirtied inode 200499 (?) on tmpfs
	[ 3156.631049] chromium(31986): dirtied inode 202600 (?) on tmpfs
	[ 3156.955755] CompositorTileW(32229): dirtied inode 206522 (?) on tmpfs
	[ 3156.957365] CompositorTileW(32227): dirtied inode 200492 (?) on tmpfs
	[ 3156.957452] CompositorTileW(32227): dirtied inode 200493 (?) on tmpfs
	[ 3156.957611] CompositorTileW(32227): dirtied inode 200494 (?) on tmpfs
	[ 3156.957674] CompositorTileW(32227): dirtied inode 200495 (?) on tmpfs
	[ 3156.957732] CompositorTileW(32227): dirtied inode 200496 (?) on tmpfs
	[ 3156.976791] chromium(32222): dirtied inode 200505 (?) on tmpfs
	[ 3160.332970] jbd2/dm-0-8(247): WRITE block 243646104 on dm-0 (8 sectors)
	[ 3160.332996] jbd2/dm-0-8(247): WRITE block 243646112 on dm-0 (8 sectors)
	[ 3160.333001] jbd2/dm-0-8(247): WRITE block 243646120 on dm-0 (8 sectors)
	[ 3160.333005] jbd2/dm-0-8(247): WRITE block 243646128 on dm-0 (8 sectors)
	[ 3160.333009] jbd2/dm-0-8(247): WRITE block 243646136 on dm-0 (8 sectors)
	[ 3160.333013] jbd2/dm-0-8(247): WRITE block 243646144 on dm-0 (8 sectors)
	[ 3160.333017] jbd2/dm-0-8(247): WRITE block 243646152 on dm-0 (8 sectors)
	[ 3160.333020] jbd2/dm-0-8(247): WRITE block 243646160 on dm-0 (8 sectors)
	[ 3160.334723] jbd2/dm-0-8(247): WRITE block 243646168 on dm-0 (8 sectors)
	[ 3161.123678] chromium(31986): dirtied inode 208922 (?) on tmpfs
	[ 3161.127553] chromium(32222): dirtied inode 208920 (?) on tmpfs
	[ 3161.141244] chromium(32222): dirtied inode 208553 (?) on tmpfs
	[ 3161.144833] chromium(32222): dirtied inode 208554 (?) on tmpfs
	[ 3161.151486] chromium(31986): dirtied inode 208538 (?) on tmpfs
	[ 3161.166848] chromium(32222): dirtied inode 208555 (?) on tmpfs
	[ 3162.213594] chromium(31986): dirtied inode 206574 (?) on tmpfs
	[ 3162.216283] chromium(31986): dirtied inode 200524 (?) on tmpfs
	[ 3162.216585] chromium(31986): dirtied inode 206579 (?) on tmpfs
	[ 3165.946070] kworker/u16:2(28238): WRITE block 125336 on dm-0 (8 sectors)
	[ 3166.162056] LevelDBEnv(32276): dirtied inode 203262 (LOG) on tmpfs
	[ 3166.162837] LevelDBEnv(32276): dirtied inode 200538 (000094.ldb) on tmpfs
	[ 3166.164648] LevelDBEnv(32276): dirtied inode 57331 (MANIFEST-000001) on tmpfs
	[ 3166.548897] BrowserBlocking(31897): dirtied inode 11665558 (?) on dm-0
	[ 3166.548906] BrowserBlocking(31897): dirtied inode 11665558 (?) on dm-0
	[ 3171.319264] jbd2/dm-0-8(247): WRITE block 243646176 on dm-0 (8 sectors)
	[ 3171.319290] jbd2/dm-0-8(247): WRITE block 243646184 on dm-0 (8 sectors)
	[ 3171.319295] jbd2/dm-0-8(247): WRITE block 243646192 on dm-0 (8 sectors)
	[ 3171.319299] jbd2/dm-0-8(247): WRITE block 243646200 on dm-0 (8 sectors)
	[ 3171.319303] jbd2/dm-0-8(247): WRITE block 243646208 on dm-0 (8 sectors)
	[ 3171.319306] jbd2/dm-0-8(247): WRITE block 243646216 on dm-0 (8 sectors)
	[ 3171.319310] jbd2/dm-0-8(247): WRITE block 243646224 on dm-0 (8 sectors)
	[ 3171.321060] jbd2/dm-0-8(247): WRITE block 243646232 on dm-0 (8 sectors)
	[ 3175.972348] kworker/u16:1(2364): WRITE block 293601296 on dm-0 (8 sectors)
	[ 3175.972370] kworker/u16:1(2364): WRITE block 373293184 on dm-0 (8 sectors)
	[ 3175.972376] kworker/u16:1(2364): WRITE block 373293384 on dm-0 (8 sectors)
	[ 3175.972381] kworker/u16:1(2364): WRITE block 373293424 on dm-0 (8 sectors)
	[ 3175.972385] kworker/u16:1(2364): WRITE block 373293432 on dm-0 (8 sectors)
	[ 3175.972390] kworker/u16:1(2364): WRITE block 373358992 on dm-0 (8 sectors)
	[ 3175.972396] kworker/u16:1(2364): WRITE block 406847512 on dm-0 (8 sectors)
	[ 3175.972401] kworker/u16:1(2364): WRITE block 482346168 on dm-0 (8 sectors)

**Comment by graysky2** [comment] 2016-06-24 06:49
Are we good to close this as not a bug?

**Comment by ActualizeInMaterial** [comment] 2016-06-24 08:42
Well uhm... I don't know what dm-0 is(probably device mapper 0? i haven't looked into overlayfs) but it seems like it's his HDD(maybe LUKS-ed?), but... something chrome/chromium related is writing to it:

```
[ 3156.233879] Chrome_DBThread(31898): dirtied inode 11665664 (?) on dm-0
[ 3166.548906] BrowserBlocking(31897): dirtied inode 11665558 (?) on dm-0
```

As to how this happens (symlinks from profile to something on disk? but this seems unlikely) I've no idea.
Maybe `lsof|grep chrom` would show some obvious culprit paths? On my computer:
```bash
lsof|grep chrom|grep -vE "($USER-chromium|/dev/shm/|/usr/lib/| /tmp|/dev/|/proc|/usr/share/fonts/)" | less
```

of potential interest:
```
/usr/share/mime/mime.cache
/var/cache/fontconfig/8d4af663993b81a124ee82e610bb31f9-le64.cache-7
/var/tmp/etilqs_875e1690b6cd96a (deleted)
```
I'm guessing the above(except the /var/tmp/ one) are not opened for write.

Or to list only files opened for write(this doesn't seem reliable?):

```bash
lsof | grep chrom|grep -e "[[:digit:]]\+w"|grep -v " /run/user/`id -u "$USER"`/${USER}-chromium/" | less
```
All I see here is `pipe` ones which is good.

[code taken from here](https://unix.stackexchange.com/questions/16705/find-out-what-processes-are-writing-to-hard-drive)


Or this is even better for it lists files opened for read and write (`u`):

```bash
lsof | grep chrom|grep -e " [[:digit:]]\+[wu]\{1\} "|grep -v " /run/user/`id -u "$USER"`/${USER}-chromium/" | grep -vE '( /tmp| /dev/)' | less
```
[code taken from here](https://unix.stackexchange.com/questions/16705/find-out-what-processes-are-writing-to-hard-drive)

Ignoring the other irrelevant non-path stuff, only this file seems relevant(which is in tmpfs for me):
```
chromium  1317         z  143u      REG               0,38      8200      11137 /var/tmp/etilqs_875e1690b6cd96a (deleted)
```

**Comment by andresmrm** [comment] 2016-06-24 11:08
@graysky2 
I find hard to believe that the `Total_LBAs_Written` value from `smartctl` command would count writes that are not really being written to the HDD. AFAIK, this values comes form the HDD firmware.

@ActualizeInMaterial 
Thanks for the commands! I'm not used to `lsof`, but it seems to run once and close. What if a write happens after it has closed (or between runs). I had this problem with `iotop` and had to right an script to consolidate its output.
The last command is outputting some lines that maybe are relevant:

	/home/<user>/.pki/nssdb/cert9.db
	/home/<user>/.pki/nssdb/key4.db
	/var/tmp/etilqs_777fd474f7848db5 (deleted)

The first two files weren't modified recently.
How do I know if the last one is in a tmpfs? `df -h` isn't displaying it as so...

**Comment by ActualizeInMaterial** [comment] 2016-06-24 11:13
For me, I symlinked `~/.pki` to `/tmp` and `/var/tmp` is tmpfs
You could try that(temporarily? I'm unsure(forgot?) what `.pki` does, tbh, i just figured it's not that important so I put it in tmpfs), if you want and I'm guessing you won't see any more writes.

`lsof` just lists currently held-open files which should be good enough for our purposes here.

```
$ df /var/tmp
Filesystem      Size  Used Avail Use% Mounted on
tmpfs            14G   24K   14G   1% /var/tmp
```

**Comment by andresmrm** [comment] 2016-06-24 12:14
Thanks again!

Not sure if you use Arch Linux, but:

> Do not use [tmpfs] on /var/tmp, because that folder is meant for temporary files that are preserved across reboots.

from: https://wiki.archlinux.org/index.php/Tmpfs

So I mounted `.pki` and `/var/tmp` with asd.

I tested Chromium again and It still seems to write a few KBs in the first minute, but then It seems to stop. I still need to test it with a real Hangout call (I think it was writing many MBs while on them).

**Comment by ActualizeInMaterial** [comment] 2016-06-24 12:20
Thanks for that, I'll look into it to see if I should be worried. I am using Manjaro which is basically Arch Linux with an easy install I guess and other stuff like mhwd - doesn't matter.
For me, I also have `~/.cache` in tmpfs. For this I'm aware of the caveats, I suppose :)

(I haven't tested chromium with hangouts or its plugin)

**Comment by ActualizeInMaterial** [comment] 2016-06-24 12:30
If you want to see the contents of those deleted files that chromium is holding open(but it deleted - a trick used by libvte terminals like* xfce4-terminal in /tmp)  then you could:

```bash
$ lsof /var/tmp
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF   NODE NAME
chromium 1317    z  143u   REG   0,38    16400  11137 /var/tmp/etilqs_875e1690b6cd96a (deleted)
chromium 1317    z  179u   REG   0,38     2052 438657 /var/tmp/etilqs_8be3500487470e39 (deleted)
```
then I guess look at PID 1317's file descriptor 143 via `mcview /proc/1317/fd`  looks like some sort of a temporary database of what you're or was browsing (such as the title and urls of the webpages).


\* Look at xfce4-terminal:
`xfce4-ter  872    z   44u   REG   0,37    10831 1407583 /tmp/vte44P8IY (deleted)`
I guess good thing /tmp is on tmpfs  else everything you see on terminal is written to disk.
ain't that something heh

**Comment by graysky2** [comment] 2016-06-24 18:55
> I find hard to believe that the Total_LBAs_Written value from smartctl command would count writes that are not really being written to the HDD. AFAIK, this values comes form the HDD firmware.

@andresmrm - AFAIK, I have the mount setup correctly so if if you suspect foul play on the part of the file system, I don't think psd is to blame as it just setup them up.  I am closing.

**Closed by graysky2** 2016-06-24 18:55 UTC

**Comment by andresmrm** [comment] 2016-06-24 19:07
@ActualizeInMaterial - Thanks for the extra tips. =)

@graysky2 - I don't suspect the file system... Firefox mount seems to work perfectly here. What I think is happening is Chromium writing to places that PSD is not covering (`/var/tmp` would be an example).

**Comment by ActualizeInMaterial** [comment] 2016-06-24 19:57
In truth though, I don't see psd handling the other aforementioned writes, considering it doesn't try to handle the (separate)cache one either:

>Note: Some browsers such as Chrome/Chromium, Firefox (since v21), Midori, and Rekonq actually keeps their cache directories separately from their profile directory. It is not within the scope of profile-sync-daemon to modify this behavior;

src: https://wiki.archlinux.org/index.php/Profile-sync-daemon#Design_goals_and_benefits_of_psd

**Comment by andresmrm** [comment] 2016-06-24 20:14
Good point. Maybe my problem is not related with the profile, but with the cache (or some kind of cache). (I'm already mounting `~/.cache` with asd)
I only think it would be good to have a list of places that should be mounted to tmpfs to avoid Chromium from writing to disc...
